-- Additive compatibility migration for an existing PostgreSQL rag_chunks table.
--
-- This migration does not re-embed rows and does not infer embedding_model.
-- Model provenance must be supplied by the operator or by a future ingest run.
-- Apply with the migration role before AI_DB_SCHEMA_MODE=managed.

ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS content_tsv tsvector
        GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS source_type text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS source_uri text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS topic_key text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS content_hash text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS chunk_hash text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS embedding_model text;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS embedding_dim integer;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS embedding_version integer DEFAULT 2;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS chunking_version integer DEFAULT 1;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS quality_score numeric DEFAULT 0.50;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS valid_from timestamptz;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS valid_to timestamptz;
ALTER TABLE rag_chunks
    ADD COLUMN IF NOT EXISTS expires_at timestamptz;

-- These values are directly derivable from existing columns. Do not populate
-- embedding_model because the legacy table has no trustworthy provenance.
UPDATE rag_chunks
SET metadata = coalesce(meta, '{}'::jsonb)
WHERE (metadata IS NULL OR metadata = '{}'::jsonb)
  AND meta IS NOT NULL
  AND meta <> '{}'::jsonb;

UPDATE rag_chunks
SET source_uri = source_url
WHERE source_uri IS NULL
  AND source_url IS NOT NULL;

UPDATE rag_chunks
SET embedding_dim = vector_dims(embedding)
WHERE embedding IS NOT NULL
  AND (embedding_dim IS NULL OR embedding_dim <> vector_dims(embedding));

CREATE INDEX IF NOT EXISTS idx_rag_chunks_content_tsv
    ON rag_chunks USING gin (content_tsv);
CREATE INDEX IF NOT EXISTS idx_rag_chunks_metadata
    ON rag_chunks USING gin (metadata);

CREATE TABLE IF NOT EXISTS rag_retrieval_events (
    event_id bigint generated by default as identity primary key,
    user_query text NOT NULL,
    intent text,
    rewritten_queries jsonb DEFAULT '[]'::jsonb,
    metadata_filter jsonb DEFAULT '{}'::jsonb,
    retrieved_chunk_ids jsonb DEFAULT '[]'::jsonb,
    selected_chunk_ids jsonb DEFAULT '[]'::jsonb,
    scores jsonb DEFAULT '[]'::jsonb,
    latency_ms integer,
    success boolean NOT NULL DEFAULT true,
    error_type text,
    created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rag_retrieval_events_created_at
    ON rag_retrieval_events (created_at);
CREATE INDEX IF NOT EXISTS idx_rag_retrieval_events_success_error
    ON rag_retrieval_events (success, error_type);
