#!/usr/bin/env python3
"""Build latency baseline from multiple smoke summary reports."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Aggregate smoke summary reports into a baseline JSON."
    )
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help="One or more summary JSON files generated by smoke_chatbot_quality.py --summary-output",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output path for aggregated baseline JSON.",
    )
    return parser.parse_args()


def _avg(values: List[float]) -> Optional[float]:
    if not values:
        return None
    return round(sum(values) / len(values), 6)


def _collect_metric_values(reports: List[Dict[str, Any]], path: List[str]) -> List[float]:
    values: List[float] = []
    for report in reports:
        current: Any = report
        for key in path:
            if not isinstance(current, dict) or key not in current:
                current = None
                break
            current = current[key]
        if isinstance(current, (int, float)):
            values.append(float(current))
    return values


def _build_endpoint_baseline(reports: List[Dict[str, Any]], endpoint_key: str) -> Dict[str, Any]:
    base_path = ["summary", endpoint_key]
    return {
        "pass_rate": _avg(_collect_metric_values(reports, base_path + ["pass_rate"])),
        "error_rate": _avg(_collect_metric_values(reports, base_path + ["error_rate"])),
        "timeout_rate": _avg(_collect_metric_values(reports, base_path + ["timeout_rate"])),
        "latency_ms": {
            "p50": _avg(_collect_metric_values(reports, base_path + ["latency_ms", "p50"])),
            "p95": _avg(_collect_metric_values(reports, base_path + ["latency_ms", "p95"])),
            "p99": _avg(_collect_metric_values(reports, base_path + ["latency_ms", "p99"])),
            "avg": _avg(_collect_metric_values(reports, base_path + ["latency_ms", "avg"])),
        },
    }


def _load_reports(input_paths: List[str]) -> List[Dict[str, Any]]:
    reports: List[Dict[str, Any]] = []
    for path_str in input_paths:
        path = Path(path_str)
        reports.append(json.loads(path.read_text(encoding="utf-8")))
    return reports


def main() -> int:
    args = parse_args()
    reports = _load_reports(args.inputs)
    if len(reports) < 2:
        raise ValueError("At least two summary reports are required for baseline.")

    baseline = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "input_reports": [str(Path(p).resolve()) for p in args.inputs],
        "run_count": len(reports),
        "metrics": {
            "overall_error_rate": _avg(
                _collect_metric_values(reports, ["summary", "overall_error_rate"])
            ),
            "overall_timeout_rate": _avg(
                _collect_metric_values(reports, ["summary", "overall_timeout_rate"])
            ),
            "completion": _build_endpoint_baseline(reports, "completion_metrics"),
            "stream": _build_endpoint_baseline(reports, "stream_metrics"),
        },
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(baseline, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"baseline saved: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
