#!/usr/bin/env python3
"""Build latency baseline from multiple smoke summary reports."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

REPORTS_DIR = Path(__file__).resolve().parents[2] / "reports"
PRESET_INPUTS = {
    "regmix_100": [
        REPORTS_DIR / "smoke_chatbot_quality_regmix_100_baseline_summary.json",
        REPORTS_DIR / "smoke_chatbot_quality_regmix_100_v3_summary.json",
    ],
    "regulations_20": [
        REPORTS_DIR / "smoke_chatbot_quality_regulations_20_baseline_summary.json",
        REPORTS_DIR / "smoke_chatbot_quality_regulations_20_v1_summary.json",
    ],
}
PRESET_OUTPUTS = {
    "regmix_100": REPORTS_DIR / "smoke_latency_baseline_regmix_100.json",
    "regulations_20": REPORTS_DIR / "smoke_latency_baseline_regulations_20.json",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Aggregate smoke summary reports into a baseline JSON."
    )
    parser.add_argument(
        "--preset",
        choices=sorted(PRESET_INPUTS),
        default=None,
        help="Use canonical report inputs/output for a named baseline preset.",
    )
    parser.add_argument(
        "--inputs",
        nargs="+",
        default=None,
        help="One or more summary JSON files generated by smoke_chatbot_quality.py --summary-output",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output path for aggregated baseline JSON.",
    )
    return parser.parse_args()


def _avg(values: List[float]) -> Optional[float]:
    if not values:
        return None
    return round(sum(values) / len(values), 6)


def _collect_metric_values(
    reports: List[Dict[str, Any]], path: List[str]
) -> List[float]:
    values: List[float] = []
    for report in reports:
        current: Any = report
        for key in path:
            if not isinstance(current, dict) or key not in current:
                current = None
                break
            current = current[key]
        if isinstance(current, (int, float)):
            values.append(float(current))
    return values


def _build_endpoint_baseline(
    reports: List[Dict[str, Any]], endpoint_key: str
) -> Dict[str, Any]:
    base_path = ["summary", endpoint_key]
    return {
        "pass_rate": _avg(_collect_metric_values(reports, base_path + ["pass_rate"])),
        "error_rate": _avg(_collect_metric_values(reports, base_path + ["error_rate"])),
        "timeout_rate": _avg(
            _collect_metric_values(reports, base_path + ["timeout_rate"])
        ),
        "latency_ms": {
            "p50": _avg(
                _collect_metric_values(reports, base_path + ["latency_ms", "p50"])
            ),
            "p95": _avg(
                _collect_metric_values(reports, base_path + ["latency_ms", "p95"])
            ),
            "p99": _avg(
                _collect_metric_values(reports, base_path + ["latency_ms", "p99"])
            ),
            "avg": _avg(
                _collect_metric_values(reports, base_path + ["latency_ms", "avg"])
            ),
        },
    }


def _load_reports(input_paths: List[str]) -> List[Dict[str, Any]]:
    reports: List[Dict[str, Any]] = []
    for path_str in input_paths:
        path = Path(path_str)
        reports.append(json.loads(path.read_text(encoding="utf-8")))
    return reports


def _resolve_inputs(args: argparse.Namespace) -> List[str]:
    if args.inputs:
        return list(args.inputs)
    if args.preset:
        return [str(path) for path in PRESET_INPUTS[args.preset]]
    raise ValueError("Either --inputs or --preset must be provided.")


def _resolve_output(args: argparse.Namespace) -> Path:
    if args.output:
        return Path(args.output)
    if args.preset:
        return PRESET_OUTPUTS[args.preset]
    raise ValueError("Either --output or --preset must be provided.")


def main() -> int:
    args = parse_args()
    input_paths = _resolve_inputs(args)
    output_path = _resolve_output(args)
    reports = _load_reports(input_paths)
    if len(reports) < 2:
        raise ValueError("At least two summary reports are required for baseline.")

    baseline = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "input_reports": [str(Path(p).resolve()) for p in input_paths],
        "run_count": len(reports),
        "metrics": {
            "overall_error_rate": _avg(
                _collect_metric_values(reports, ["summary", "overall_error_rate"])
            ),
            "overall_timeout_rate": _avg(
                _collect_metric_values(reports, ["summary", "overall_timeout_rate"])
            ),
            "completion": _build_endpoint_baseline(reports, "completion_metrics"),
            "stream": _build_endpoint_baseline(reports, "stream_metrics"),
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(baseline, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"baseline saved: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
